version: '3'
services:
  web:
    image: nginx:latest
    container_name: file_web_server
    ports:
      - '8001:80'
    volumes:
      - ./file_web_server:/srv
      - ./file_web_server.conf:/etc/nginx/conf.d/default.conf
  web2:
    image: nginx:alpine
    container_name: app_server
    ports:
      - '8000:80'
    volumes:
      - ./app_server:/usr/share/nginx/html
      - ./app_server.conf:/etc/nginx/nginx.conf
